version: '2'
services:
    traefik:
        image: traefik:1.4
        command: --web 
        ports:
          - 80:80
          - 8080:8080
        volumes:
          - ./traefik/traefik.toml:/etc/traefik/traefik.toml
